language: cpp
compiler: gcc

matrix:
    include:
        - name: switch-host-gcc/gcc-4.7
          dist: trusty
          install:
              - sudo apt-get install cmake g++-4.7-multilib gcc-4.7-plugin-dev libboost-dev
              - sudo sed -e 's| thread_local| my_thread_local|' -i /usr/lib/gcc/x86_64-linux-gnu/4.7/plugin/include/tree.h
          script:
              - patch -p1 < build-aux/gcc-8.3.0.patch
              - patch -p1 < build-aux/gcc-6.5.0.patch
              - patch -p1 < build-aux/gcc-5.4.0.patch
              - patch -p1 < build-aux/gcc-4.7.3.patch
              - ./switch-host-gcc.sh /usr/bin/gcc-4.7


        - name: switch-host-gcc/gcc-4.8
          dist: trusty
          install:
              - sudo apt-get install cmake g++-4.8-multilib gcc-4.8-plugin-dev libboost-dev
          script:
              - patch -p1 < build-aux/gcc-8.3.0.patch
              - patch -p1 < build-aux/gcc-6.5.0.patch
              - patch -p1 < build-aux/gcc-5.4.0.patch
              - ./switch-host-gcc.sh /usr/bin/gcc-4.8


        - name: switch-host-gcc/gcc-5
          dist: xenial
          install:
              - sudo apt-get install cmake g++-5-multilib gcc-5-plugin-dev gcc-multilib libboost-dev
          env:
              - CC=/usr/bin/gcc-5
              - CXX=/usr/bin/g++-5
          script:
              - patch -p1 < build-aux/gcc-8.3.0.patch
              - patch -p1 < build-aux/gcc-6.5.0.patch
              - patch -p1 < build-aux/gcc-5.4.0.patch
              - ./switch-host-gcc.sh /usr/bin/gcc-5


        - name: switch-host-gcc/gcc-8
          dist: bionic
          install:
              - sudo apt-get install cmake g++-8-multilib gcc-8-plugin-dev gcc-multilib libboost-dev
          env:
              - CC=/usr/bin/gcc-8
              - CXX=/usr/bin/g++-8
          script:
              - patch -p1 < build-aux/gcc-8.3.0.patch
              - ./switch-host-gcc.sh /usr/bin/gcc-8


        - name: switch-host-gcc/gcc-10
          dist: focal
          install:
              - sudo apt-get install cmake g++-10-multilib gcc-10-plugin-dev gcc-multilib libboost-dev
          env:
              - CC=/usr/bin/gcc-10
              - CXX=/usr/bin/g++-10
          script:
              - ./switch-host-gcc.sh /usr/bin/gcc-10


        - name: switch-host-llvm/llvm-6
          dist: xenial
          install:
              - sudo apt-get install clang-6.0 cmake llvm-6.0-dev gcc-multilib libboost-dev
          env:
              - CC=/usr/bin/clang-6.0
              - CXX=/usr/bin/clang++-6.0
          script:
              - git clone --depth 1 https://github.com/VeriFIT/ProStatA.git passes-src
              - sed -e 's|^ *if(.*VERSION_GREATER_EQUAL.*)$|if(FALSE)|' -i build-aux/common.cmake passes-src/passes/CMakeLists.txt
              - ./switch-host-llvm.sh /usr/lib/llvm-6.0/cmake


        - name: switch-host-llvm/llvm-8
          dist: bionic
          install:
              - sudo apt-get install clang-8 cmake llvm-8-dev gcc-multilib libboost-dev
          env:
              - CC=/usr/bin/clang-8
              - CXX=/usr/bin/clang++-8
          script:
              - ./switch-host-llvm.sh /usr/lib/llvm-8/cmake


        - name: switch-host-llvm/llvm-10
          dist: focal
          install:
              - sudo apt-get install clang-10 cmake llvm-10-dev gcc-multilib libboost-dev
          env:
              - CC=/usr/bin/clang-10
              - CXX=/usr/bin/clang++-10
          script:
              - ./switch-host-llvm.sh /usr/lib/llvm-10/cmake


        - name: debug-build/gcc-7
          dist: bionic
          install:
              - sudo apt-get install cmake g++-7-multilib gcc-7-plugin-dev gcc-multilib libboost-dev
          env:
              - CC=/usr/bin/gcc-7
              - CXX=/usr/bin/g++-7
              - GCC_HOST=/usr/bin/gcc-7
          script:
              - patch -p1 < build-aux/gcc-8.3.0.patch
              - make -C cl -s -j5 'CMAKE=cmake -D CL_DEBUG=ON' check
              - make -C sl -s -j5 'CMAKE=cmake -D SL_DEBUG=ON' check


        - name: expensive-tests/gcc-8
          dist: bionic
          install:
              - sudo apt-get install cmake g++-8-multilib gcc-8-plugin-dev libboost-dev
          env:
              - CC=/usr/bin/gcc-8
              - CXX=/usr/bin/g++-8
              - GCC_HOST=/usr/bin/gcc-8
          script:
              - patch -p1 < build-aux/gcc-8.3.0.patch
              - make -C cl -s -j5
              - make -C sl -s -j5 'CMAKE=cmake -D TEST_ONLY_FAST=OFF' check


        - name: csbuild/gcc-4.8
          dist: trusty
          before_install:
              - sudo apt-get update -qq
              - sudo apt-get install -qq apt-transport-https
              - echo "deb [trusted=yes] https://kdudka.fedorapeople.org/csbuild trusty contrib" | sudo tee -a /etc/apt/sources.list
              - sudo apt-get update -qq

          install:
              - sudo apt-get install -qq -y --force-yes csbuild
              - sudo apt-get install cmake g++-4.8-multilib gcc-4.8-plugin-dev libboost-dev

          script:
              - if git diff "$TRAVIS_COMMIT_RANGE" >/dev/null; then csbuild --git-commit-range "$TRAVIS_COMMIT_RANGE" -c "make distclean && make -j9" --git-bisect --print-current --print-fixed; fi
